import { COLORS } from "@/styles/StyleTokens";
import { StyleSheet } from "react-native";

export const ConfirmModalstyles = StyleSheet.create({
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(22, 23, 27, 0.6)",
    borderRadius: 8,
    zIndex: 10,
  },
  box: {
    alignItems: "center",
    gap: 16,
    borderRadius: 8,
    padding: 20,
    minWidth: 240,
    backgroundColor: COLORS.paper,
  },
  message: {
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
    color: COLORS.ink,
  },
  buttonRow: { flexDirection: "row", gap: 8, width: "100%" },
  button: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 4,
    alignItems: "center",
  },
  pressed: { opacity: 0.85 },
  buttonText: { fontSize: 14, fontWeight: "600", color: COLORS.buttonText },
});

export const EditModalstyles = StyleSheet.create({
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(22, 23, 27, 0.6)",
    zIndex: 10,
  },
  box: {
    alignItems: "center",
    gap: 12,
    borderRadius: 8,
    padding: 20,
    minWidth: 240,
    backgroundColor: COLORS.paper,
  },
  row: { flexDirection: "row", alignItems: "center", gap: 8, width: "100%" },
  quantityInput: {
    width: 56,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: COLORS.paperEdge,
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 14,
    color: COLORS.ink,
  },
  textInput: {
    flex: 1,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: COLORS.paperEdge,
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 14,
    color: COLORS.ink,
  },
  addButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.bgPanelEdge,
  },
  pressed: { opacity: 0.7 },
  buttonRow: { flexDirection: "row", gap: 8, width: "100%", marginTop: 8 },
  button: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 4,
    alignItems: "center",
  },
  buttonText: { fontSize: 14, fontWeight: "600" },
});

export const RegisterModalstyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 16,
  },
  cardWrapper: {
    width: "100%",
    maxWidth: 384,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.45,
    shadowRadius: 24,
    elevation: 10,
  },
  card: {
    borderRadius: 6,
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 20,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  title: {
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  label: {
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  input: {
    width: "100%",
    borderWidth: 1,
    borderRadius: 4,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
  },
  error: {
    fontSize: 12,
    marginTop: 4,
  },
  divider: {
    borderTopWidth: 1.5,
    borderStyle: "dashed",
    marginVertical: 16,
  },
  actions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 12,
  },
  cancelText: {
    fontSize: 14,
    fontWeight: "600",
  },
  submitButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 4,
  },
  submitText: {
    fontSize: 14,
    fontWeight: "600",
  },
});
